### ISSUE TITLE
Abstraction needed for StructJuMP compatibility

### ISSUE THREAD

**Issue by jd-lara** [JuliaStochOpt/ParameterJuMP.jl#48]
Currently, the function `enable_parameters` only takes JuMP.Models. In order to be able to have sub-problems with Parameters in a StructJuMP `StructuredModel` this function would have to accept any subtype `<: JuMP.AbstractModel`. 

This subtyping might be needed in other functions too. 

see here https://github.com/NREL/PowerSimulations.jl/pull/111#issuecomment-476776068

cc. @jmaack24

**Comment by joaquimg** [comment]
Changing the type is not enough.
We will need to allow `StructuredModel` to support parameters.

**Comment by joaquimg** [comment]
Not sure I got the problem

**Comment by jmaack24** [comment]
Let me see if I can elaborate a bit.  In PowerSimulations.jl, the model creation is independent of the specific model implementation.  That is, it should work for any model that is a subtype of `JuMP.AbstractModel` and implements the appropriate functions.  `StructJuMP.StructuredModel` is such a model type.

However, the ParameterJuMP code seems to be built on the concrete type `JuMP.Model`.  Therefore when the PowerSimulations code calls `ParameterJuMP.enable_parameters(JuMPmodel)` and `JuMPmodel` is a `StructJuMP.StructuredModel`, Julia is going to complain since `ParameterJuMP.enable_parameter` only takes `JuMP.Model` type.

Briefly looking through the ParameterJuMP code (so I may be wrong about this) and the README, I don't see any reason why ParameterJuMP cannot be written to dispatch on the various JuMP abstract types so that it would work with any subtype of JuMP.AbstractModel that implements the appropriate functions.  This is really the change we're asking for.  I recognize this is probably a rather large change.

Hope that makes this issue clearer.

**Comment by joaquimg** [comment]
That's more clear.

One point,
ParameterJuMP needs to keep its data somewhere in them `AbstractModel`, this place existis in `JuMP.Model`, its the dictionary field `.ext`.
`StructJuMP.StructuredModel` does not have such field.
So we need to modify `StructJuMP.StructuredModel` so that its able to hold and store parameters.

From what I understand, `StructuredModel` rebuild the entire problem everytime it needs to solve.
If that is true, integrating parameters should be easy.
Moreover, `StructuredModel` creates a `ParametricModel` which uses param, we just have to choose where to intercept the call.

Can I ask the reason why you are using `StructuredModel`? Sometime you use regular `Model`, right?

**Comment by jmaack24** [comment]
The short answer is we are trying to make PowerSimulations.jl runnable on HPC resources and StructJuMP is a way to do that as we can exploit the sparsity structure to parallelize the optimization.

Looking at the StructJuMP code, it only creates a ParametricModel when calling `StructJuMP.BendersBridge` which I assume is using Benders decomposition to solve the given model.  But we are trying to use other solution techniques (ProgressiveHedging and PIPS-NLP) which can easily be deployed on HPC.

Also, I can provide an example of using PowerSimulations (and PowerSystems) to build a `StructuredModel` for testing if that would be helpful.

**Comment by joaquimg** [comment]
Ok, that is a good start.
I'd recommend  writing a simple structured model with 2 vars and two params, independent od PowerSimulations right now.
Are you convinced we should modify the `StructuredModel`?

**Comment by jmaack24** [comment]
If modifying `StructuredModel` is the easiest way to implement it then that works for me.  We just need to ask StructJuMP for that change.

I will get you the simple 2 variable, 2 parameter example tomorrow.

**Comment by joaquimg** [comment]
If you have a suggestion for that in ParameterJuMP, let me know, but I think that won´t be trivial.

**Comment by joaquimg** [comment]
Maybe @blegat has some ideas

**Comment by jmaack24** [comment]
I agree.  Adding something in ParameterJuMP to track its data is probably not trivial.  I don't really have any other ideas.

**Comment by jmaack24** [comment]
Here's the StructJuMP example:
~~~julia
using StructJuMP
using ParameterJuMP

sm = StructuredModel(num_scenarios=2)
enable_parameters(sm)

@variable(sm, x >= 0.0)
@variable(sm, y >= 0.0)
@objective(sm, Min, x + y)
a = Parameter(sm, 2.0)
b = Parameter(sm, 16.0)
@constraint(x + y >= a)
@constraint(x + y <= b)
~~~

**Comment by blegat** [comment]
Adding the `ext` field in StructuredModel seems reasonable. PR welcome.
In the long term, we should have a documented API in JuMP instead of relying on the existence of a field.
